# Generated by Django 6.0.4 on 2026-04-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_contact',
            field=models.BooleanField(default=True),
        ),
    ]
