# Generated by Django 6.0.4 on 2026-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
