# Generated by Django 6.0.4 on 2026-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_campus_listing_image_url_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='listings/'),
        ),
    ]
