# Generated by Django 6.0.4 on 2026-04-30 20:11

from django.db import migrations, models


def backfill_hidden_status(apps, schema_editor):
    Listing = apps.get_model("marketplace", "Listing")
    Listing.objects.filter(is_available=False).update(status="hidden")


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('hidden', 'Hidden')], default='available', max_length=12),
        ),
        migrations.RunPython(backfill_hidden_status, migrations.RunPython.noop),
    ]
