# Generated by Django 6.0.4 on 2026-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_marketplace_transaction_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='overdue_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
